In [57]:
import torch
import torch.nn.functional as F

In [58]:
shape1, shape2 = 4, 4
data = torch.randn(shape1, shape2)
q, r = torch.linalg.qr(data)
print(q, "\n", f"Q: {q.shape}", f"R: {r.shape}", sep='')
print(q @ q.t())
print(q.t() @ q)

tensor([[-0.6768,  0.1861,  0.3390,  0.6265],
        [-0.3568, -0.6498, -0.6518,  0.1601],
        [-0.2035,  0.7336, -0.6421, -0.0903],
        [ 0.6109,  0.0709, -0.2191,  0.7575]])
Q: torch.Size([4, 4])R: torch.Size([4, 4])
tensor([[ 1.0000e+00, -9.5328e-08, -2.9728e-08,  6.5487e-08],
        [-9.5328e-08,  1.0000e+00, -2.4068e-08,  3.0310e-08],
        [-2.9728e-08, -2.4068e-08,  1.0000e+00,  1.0175e-08],
        [ 6.5487e-08,  3.0310e-08,  1.0175e-08,  1.0000e+00]])
tensor([[ 1.0000e+00, -3.2256e-09,  8.2839e-09, -4.3444e-08],
        [-3.2256e-09,  1.0000e+00,  4.6191e-08,  5.9798e-09],
        [ 8.2839e-09,  4.6191e-08,  1.0000e+00,  4.1770e-08],
        [-4.3444e-08,  5.9798e-09,  4.1770e-08,  1.0000e+00]])


In [59]:
shape1, shape2 = 5, 4
data = torch.randn(shape1, shape2)
q, r = torch.linalg.qr(data)
print(q, "\n", f"Q: {q.shape}", f"R: {r.shape}", sep='')
print(q @ q.t())
print(q.t() @ q)

tensor([[-0.3777,  0.7115,  0.0663,  0.2113],
        [-0.7097, -0.1668,  0.5128, -0.4194],
        [-0.5241, -0.3321, -0.3152,  0.6998],
        [-0.1481,  0.5462, -0.4181, -0.1974],
        [ 0.2390,  0.2394,  0.6771,  0.5008]])
Q: torch.Size([5, 4])R: torch.Size([4, 4])
tensor([[ 0.6979,  0.0947,  0.0886,  0.3752,  0.2307],
        [ 0.0947,  0.9703, -0.0278, -0.1176, -0.0724],
        [ 0.0886, -0.0278,  0.9740, -0.1101, -0.0677],
        [ 0.3752, -0.1176, -0.1101,  0.5340, -0.2866],
        [ 0.2307, -0.0724, -0.0677, -0.2866,  0.8237]])
tensor([[ 1.0000e+00, -1.2747e-07, -3.7728e-08, -9.6523e-08],
        [-1.2747e-07,  1.0000e+00,  7.6257e-08,  1.3010e-08],
        [-3.7728e-08,  7.6257e-08,  1.0000e+00, -8.0930e-08],
        [-9.6523e-08,  1.3010e-08, -8.0930e-08,  1.0000e+00]])


In [60]:
shape1, shape2 = 4, 20
data = torch.randn(shape1, shape2)
q, r = torch.linalg.qr(data)
print(q, "\n", f"Q: {q.shape}", f"R: {r.shape}", sep='')
print(q @ q.t())
print(q.t() @ q)

tensor([[-0.0617, -0.9570,  0.0815,  0.2716],
        [ 0.2440, -0.0542,  0.8819, -0.3998],
        [-0.4032, -0.2359, -0.2828, -0.8378],
        [ 0.8798, -0.1602, -0.3684, -0.2540]])
Q: torch.Size([4, 4])R: torch.Size([4, 20])
tensor([[ 1.0000e+00,  3.9038e-08, -5.8699e-08, -1.5726e-07],
        [ 3.9038e-08,  1.0000e+00, -1.0378e-07, -5.2362e-08],
        [-5.8699e-08, -1.0378e-07,  1.0000e+00,  7.1223e-08],
        [-1.5726e-07, -5.2362e-08,  7.1223e-08,  1.0000e+00]])
tensor([[ 1.0000e+00,  9.7750e-08, -1.2295e-08, -6.3991e-08],
        [ 9.7750e-08,  1.0000e+00, -5.6131e-08, -6.0215e-08],
        [-1.2295e-08, -5.6131e-08,  1.0000e+00,  9.6916e-08],
        [-6.3991e-08, -6.0215e-08,  9.6916e-08,  1.0000e+00]])


In [61]:
import torch.nn as nn
shape1, shape2 = 4, 4
data = torch.randn(shape1, shape2)
q, r = torch.linalg.qr(data)
print(f"Q: {q.shape}", '\n', f"R: {r.shape}", sep='')
print(q)
print(r)
print(torch.norm(q, dim=-1))

q, r = torch.linalg.qr(q)
print(f"Q: {q.shape}", '\n', f"R: {r.shape}", sep='')
print(q)
print(r)
print(torch.norm(q, dim=-1))

Q: torch.Size([4, 4])
R: torch.Size([4, 4])
tensor([[-0.4147, -0.6200,  0.0565,  0.6637],
        [ 0.8282, -0.5588,  0.0425, -0.0080],
        [-0.3029, -0.4837, -0.5682, -0.5928],
        [ 0.2243,  0.2636, -0.8198,  0.4562]])
tensor([[ 0.8676, -1.5700,  0.8236,  0.5611],
        [ 0.0000, -2.8724,  2.0176,  0.5190],
        [ 0.0000,  0.0000, -1.7756, -0.6848],
        [ 0.0000,  0.0000,  0.0000, -0.1680]])
tensor([1.0000, 1.0000, 1.0000, 1.0000])
Q: torch.Size([4, 4])
R: torch.Size([4, 4])
tensor([[-0.4147, -0.6200,  0.0565,  0.6637],
        [ 0.8282, -0.5588,  0.0425, -0.0080],
        [-0.3029, -0.4837, -0.5682, -0.5928],
        [ 0.2243,  0.2636, -0.8198,  0.4562]])
tensor([[ 1.0000e+00,  7.0471e-08, -3.2305e-08, -8.2549e-08],
        [ 0.0000e+00,  1.0000e+00, -2.9692e-08, -1.0787e-08],
        [ 0.0000e+00,  0.0000e+00,  1.0000e+00,  3.5784e-08],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]])
tensor([1.0000, 1.0000, 1.0000, 1.0000])


In [62]:
shape1, shape2 = 4, 4
data = torch.randn(shape1, shape2)

print(f"Q: {q.shape}", '\n', f"R: {r.shape}", sep='')
print(q)
print(r)
print(torch.norm(q, dim=-1))

norm_data = F.normalize(q, dim=-1, p=2)
print(norm_data)
norm_data = F.normalize(q, dim=0, p=2)
print(norm_data)

Q: torch.Size([4, 4])
R: torch.Size([4, 4])
tensor([[-0.4147, -0.6200,  0.0565,  0.6637],
        [ 0.8282, -0.5588,  0.0425, -0.0080],
        [-0.3029, -0.4837, -0.5682, -0.5928],
        [ 0.2243,  0.2636, -0.8198,  0.4562]])
tensor([[ 1.0000e+00,  7.0471e-08, -3.2305e-08, -8.2549e-08],
        [ 0.0000e+00,  1.0000e+00, -2.9692e-08, -1.0787e-08],
        [ 0.0000e+00,  0.0000e+00,  1.0000e+00,  3.5784e-08],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]])
tensor([1.0000, 1.0000, 1.0000, 1.0000])
tensor([[-0.4147, -0.6200,  0.0565,  0.6637],
        [ 0.8282, -0.5588,  0.0425, -0.0080],
        [-0.3029, -0.4837, -0.5682, -0.5928],
        [ 0.2243,  0.2636, -0.8198,  0.4562]])
tensor([[-0.4147, -0.6200,  0.0565,  0.6637],
        [ 0.8282, -0.5588,  0.0425, -0.0080],
        [-0.3029, -0.4837, -0.5682, -0.5928],
        [ 0.2243,  0.2636, -0.8198,  0.4562]])


In [63]:
def qr_retraction(tan_vec):  # tan_vec, p-by-n, p <= n
    # [p, n] = tan_vec.size()
    tan_vec = tan_vec.permute(0, 2, 1)
    q, r = torch.linalg.qr(tan_vec)
    
    d = torch.diagonal(r, dim1=-2, dim2=-1)
    ph = d.sign()
    q = torch.einsum("ij,ikj->ikj", ph, q)
    q = q.permute(0, 2, 1)
    return q

q = qr_retraction(torch.randn(3, 4, 5))
print(torch.einsum('ijk, imk->ijm', q, q))


tensor([[[ 1.0000e+00,  2.6917e-08,  4.2692e-09, -5.1593e-10],
         [ 2.6917e-08,  1.0000e+00, -3.1164e-08, -4.1530e-08],
         [ 4.2692e-09, -3.1164e-08,  1.0000e+00, -1.0817e-07],
         [-5.1593e-10, -4.1530e-08, -1.0817e-07,  1.0000e+00]],

        [[ 1.0000e+00, -3.4649e-08,  2.3164e-10,  8.2514e-09],
         [-3.4649e-08,  1.0000e+00, -3.9167e-08,  2.3863e-08],
         [ 2.3164e-10, -3.9167e-08,  1.0000e+00,  3.7559e-09],
         [ 8.2514e-09,  2.3863e-08,  3.7559e-09,  1.0000e+00]],

        [[ 1.0000e+00,  3.5535e-09,  1.8177e-08,  1.4369e-08],
         [ 3.5535e-09,  1.0000e+00, -4.8728e-08, -4.5856e-09],
         [ 1.8177e-08, -4.8728e-08,  1.0000e+00,  1.7061e-09],
         [ 1.4369e-08, -4.5856e-09,  1.7061e-09,  1.0000e+00]]])


In [64]:
shape1, shape2 = 4, 8
data = torch.randn(shape1, shape2)
torch.nn.init.orthogonal_(data)
print(data.shape)
print(data @ data.t())

torch.Size([4, 8])
tensor([[ 1.0000e+00,  3.7943e-08,  1.1106e-08, -2.1132e-08],
        [ 3.7943e-08,  1.0000e+00,  2.4318e-10, -2.4585e-08],
        [ 1.1106e-08,  2.4318e-10,  1.0000e+00,  2.4070e-09],
        [-2.1132e-08, -2.4585e-08,  2.4070e-09,  1.0000e+00]])


In [65]:
data = torch.randn(3, 4, 5)
torch.linalg.qr(data[0])[0], torch.linalg.qr(data)[0][0]

(tensor([[-0.1225, -0.4192, -0.7984,  0.4144],
         [ 0.3953,  0.0134,  0.3689,  0.8411],
         [ 0.8956,  0.1013, -0.3339, -0.2761],
         [-0.1634,  0.9021, -0.3390,  0.2111]]),
 tensor([[-0.1225, -0.4192, -0.7984,  0.4144],
         [ 0.3953,  0.0134,  0.3689,  0.8411],
         [ 0.8956,  0.1013, -0.3339, -0.2761],
         [-0.1634,  0.9021, -0.3390,  0.2111]]))

In [66]:
F.normalize(data, dim=-1)[0], F.normalize(data[0], dim=-1)

(tensor([[-0.1334,  0.1972, -0.4522, -0.7834, -0.3537],
         [ 0.4565,  0.2100, -0.2117,  0.1236, -0.8291],
         [ 0.4267,  0.1770, -0.5522,  0.6938,  0.0181],
         [-0.1451, -0.5279,  0.0267, -0.0510,  0.8348]]),
 tensor([[-0.1334,  0.1972, -0.4522, -0.7834, -0.3537],
         [ 0.4565,  0.2100, -0.2117,  0.1236, -0.8291],
         [ 0.4267,  0.1770, -0.5522,  0.6938,  0.0181],
         [-0.1451, -0.5279,  0.0267, -0.0510,  0.8348]]))

In [67]:
data = torch.randn(3, 4, 5)
print(torch.max(data.flatten(1), dim=-1).values)

tensor([1.3836, 1.5646, 1.6707])


In [68]:
shape1, shape2, shape3 = 4, 4, 8
data = torch.randn(shape1, shape2, shape3)
torch.nn.init.orthogonal_(data[0])
print(data.shape)
print(data @ data.permute(0, 2, 1))

torch.Size([4, 4, 8])
tensor([[[ 1.0000e+00, -1.6400e-08,  2.2875e-08,  1.6325e-08],
         [-1.6400e-08,  1.0000e+00,  6.5359e-08, -1.0851e-08],
         [ 2.2875e-08,  6.5359e-08,  1.0000e+00, -1.6134e-08],
         [ 1.6325e-08, -1.0851e-08, -1.6134e-08,  1.0000e+00]],

        [[ 4.7944e+00, -2.9950e-01,  1.9168e+00, -4.4375e+00],
         [-2.9950e-01,  7.6753e+00, -5.5554e+00, -8.7705e-01],
         [ 1.9168e+00, -5.5554e+00,  1.0303e+01, -1.0432e+00],
         [-4.4375e+00, -8.7705e-01, -1.0432e+00,  1.3567e+01]],

        [[ 3.1671e+00,  1.1916e+00, -7.7421e-01,  1.0403e+00],
         [ 1.1916e+00,  1.0196e+01, -3.8736e-01,  4.0368e+00],
         [-7.7421e-01, -3.8736e-01,  4.8437e+00, -4.1069e+00],
         [ 1.0403e+00,  4.0368e+00, -4.1069e+00,  6.4537e+00]],

        [[ 4.7135e+00, -7.7716e-01,  3.0082e+00,  1.1763e+00],
         [-7.7716e-01,  5.6433e+00, -2.0379e+00,  4.7520e-01],
         [ 3.0082e+00, -2.0379e+00,  9.6429e+00,  3.3345e+00],
         [ 1.1763e+00,  4.7