In [2]:
import torch
import torch.nn.functional as F

In [3]:
shape1, shape2 = 4, 4
data = torch.randn(shape1, shape2)
q, r = torch.linalg.qr(data)
print(q, "\n", f"Q: {q.shape}", f"R: {r.shape}", sep='')
print(q @ q.t())
print(q.t() @ q)

tensor([[-0.2518, -0.9045, -0.3345,  0.0814],
        [ 0.7751, -0.3321,  0.1923, -0.5019],
        [-0.2423,  0.2173, -0.5857, -0.7423],
        [ 0.5264,  0.1563, -0.7128,  0.4364]])
Q: torch.Size([4, 4])R: torch.Size([4, 4])
tensor([[ 1.0000e+00, -1.9536e-08,  4.4024e-08, -8.3888e-08],
        [-1.9536e-08,  1.0000e+00,  1.2553e-08,  4.3148e-08],
        [ 4.4024e-08,  1.2553e-08,  1.0000e+00,  2.6917e-08],
        [-8.3888e-08,  4.3148e-08,  2.6917e-08,  1.0000e+00]])
tensor([[ 1.0000e+00,  7.7971e-08, -1.2321e-08,  2.4570e-08],
        [ 7.7971e-08,  1.0000e+00, -2.9737e-08,  1.1784e-08],
        [-1.2321e-08, -2.9737e-08,  1.0000e+00,  1.0299e-07],
        [ 2.4570e-08,  1.1784e-08,  1.0299e-07,  1.0000e+00]])


In [4]:
shape1, shape2 = 5, 4
data = torch.randn(shape1, shape2)
q, r = torch.linalg.qr(data)
print(q, "\n", f"Q: {q.shape}", f"R: {r.shape}", sep='')
print(q @ q.t())
print(q.t() @ q)

tensor([[-0.6783,  0.0715, -0.3040, -0.2987],
        [-0.4063, -0.1277, -0.5888,  0.1638],
        [ 0.4850,  0.2284, -0.6847,  0.3477],
        [ 0.3318, -0.6910, -0.2745, -0.5798],
        [ 0.1718,  0.6700, -0.1294, -0.6534]])
Q: torch.Size([5, 4])R: torch.Size([4, 4])
tensor([[ 0.6468,  0.3965, -0.2083, -0.0179,  0.1659],
        [ 0.3965,  0.5549,  0.2339,  0.0201, -0.1862],
        [-0.2083,  0.2339,  0.8771, -0.0105,  0.0978],
        [-0.0179,  0.0201, -0.0105,  0.9991,  0.0084],
        [ 0.1659, -0.1862,  0.0978,  0.0084,  0.9221]])
tensor([[ 1.0000e+00, -2.9066e-08,  1.1776e-08,  7.2524e-09],
        [-2.9066e-08,  1.0000e+00,  9.4010e-08, -4.1205e-08],
        [ 1.1776e-08,  9.4010e-08,  1.0000e+00, -9.0130e-08],
        [ 7.2524e-09, -4.1205e-08, -9.0130e-08,  1.0000e+00]])


In [5]:
shape1, shape2 = 4, 20
data = torch.randn(shape1, shape2)
q, r = torch.linalg.qr(data)
print(q, "\n", f"Q: {q.shape}", f"R: {r.shape}", sep='')
print(q @ q.t())
print(q.t() @ q)

tensor([[-0.0663,  0.9027, -0.2777, -0.3220],
        [-0.8425, -0.0309,  0.4472, -0.2988],
        [ 0.0210, -0.4217, -0.4963, -0.7585],
        [-0.5342, -0.0799, -0.6904,  0.4813]])
Q: torch.Size([4, 4])R: torch.Size([4, 20])
tensor([[ 1.0000e+00, -5.9470e-10, -3.2720e-08,  1.1262e-07],
        [-5.9470e-10,  1.0000e+00, -1.5531e-08, -3.3274e-08],
        [-3.2720e-08, -1.5531e-08,  1.0000e+00, -2.9590e-09],
        [ 1.1262e-07, -3.3274e-08, -2.9590e-09,  1.0000e+00]])
tensor([[ 1.0000e+00, -8.6291e-08, -1.4626e-08,  3.0473e-08],
        [-8.6291e-08,  1.0000e+00, -1.3116e-07, -2.1231e-08],
        [-1.4626e-08, -1.3116e-07,  1.0000e+00,  1.7544e-09],
        [ 3.0473e-08, -2.1231e-08,  1.7544e-09,  1.0000e+00]])


In [6]:
import torch.nn as nn
shape1, shape2 = 4, 4
data = torch.randn(shape1, shape2)
q, r = torch.linalg.qr(data)
print(f"Q: {q.shape}", '\n', f"R: {r.shape}", sep='')
print(q)
print(r)
print(torch.norm(q, dim=-1))

q, r = torch.linalg.qr(q)
print(f"Q: {q.shape}", '\n', f"R: {r.shape}", sep='')
print(q)
print(r)
print(torch.norm(q, dim=-1))

Q: torch.Size([4, 4])
R: torch.Size([4, 4])
tensor([[-0.4714, -0.0466,  0.5121, -0.7165],
        [ 0.2912, -0.7470,  0.5446,  0.2461],
        [-0.7964, -0.4052, -0.2863,  0.3457],
        [-0.2422,  0.5249,  0.5994,  0.5536]])
tensor([[-1.8752,  0.1035,  0.0536, -1.1142],
        [ 0.0000, -1.7151,  1.7249,  0.3868],
        [ 0.0000,  0.0000,  0.6307,  0.5487],
        [ 0.0000,  0.0000,  0.0000,  0.3378]])
tensor([1.0000, 1.0000, 1.0000, 1.0000])
Q: torch.Size([4, 4])
R: torch.Size([4, 4])
tensor([[-0.4714, -0.0466,  0.5121, -0.7165],
        [ 0.2912, -0.7470,  0.5446,  0.2461],
        [-0.7964, -0.4052, -0.2863,  0.3457],
        [-0.2422,  0.5249,  0.5994,  0.5536]])
tensor([[ 1.0000e+00, -7.4810e-10, -1.4485e-08,  9.3007e-09],
        [ 0.0000e+00,  1.0000e+00, -3.5555e-08,  3.1083e-08],
        [ 0.0000e+00,  0.0000e+00,  1.0000e+00, -7.9362e-08],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]])
tensor([1.0000, 1.0000, 1.0000, 1.0000])


In [7]:
shape1, shape2 = 4, 4
data = torch.randn(shape1, shape2)

print(f"Q: {q.shape}", '\n', f"R: {r.shape}", sep='')
print(q)
print(r)
print(torch.norm(q, dim=-1))

norm_data = F.normalize(q, dim=-1, p=2)
print(norm_data)
norm_data = F.normalize(q, dim=0, p=2)
print(norm_data)

Q: torch.Size([4, 4])
R: torch.Size([4, 4])
tensor([[-0.4714, -0.0466,  0.5121, -0.7165],
        [ 0.2912, -0.7470,  0.5446,  0.2461],
        [-0.7964, -0.4052, -0.2863,  0.3457],
        [-0.2422,  0.5249,  0.5994,  0.5536]])
tensor([[ 1.0000e+00, -7.4810e-10, -1.4485e-08,  9.3007e-09],
        [ 0.0000e+00,  1.0000e+00, -3.5555e-08,  3.1083e-08],
        [ 0.0000e+00,  0.0000e+00,  1.0000e+00, -7.9362e-08],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]])
tensor([1.0000, 1.0000, 1.0000, 1.0000])
tensor([[-0.4714, -0.0466,  0.5121, -0.7165],
        [ 0.2912, -0.7470,  0.5446,  0.2461],
        [-0.7964, -0.4052, -0.2863,  0.3457],
        [-0.2422,  0.5249,  0.5994,  0.5536]])
tensor([[-0.4714, -0.0466,  0.5121, -0.7165],
        [ 0.2912, -0.7470,  0.5446,  0.2461],
        [-0.7964, -0.4052, -0.2863,  0.3457],
        [-0.2422,  0.5249,  0.5994,  0.5536]])


In [8]:
def qr_retraction(tan_vec):  # tan_vec, p-by-n, p <= n
    [p, n] = tan_vec.size()
    tan_vec.t_()
    q, r = torch.linalg.qr(tan_vec)
    d = torch.diag(r, 0)
    ph = d.sign()
    q *= ph.expand_as(q)
    q.t_()

    return q

q = qr_retraction(torch.randn(4, 5))
print(q @ q.t())
print(q.t() @ q)

tensor([[ 1.0000e+00,  3.9229e-08, -3.5436e-08, -3.5576e-08],
        [ 3.9229e-08,  1.0000e+00,  4.5683e-08,  5.2517e-08],
        [-3.5436e-08,  4.5683e-08,  1.0000e+00, -4.7265e-08],
        [-3.5576e-08,  5.2517e-08, -4.7265e-08,  1.0000e+00]])
tensor([[ 0.5009, -0.1392,  0.4102,  0.1805,  0.1726],
        [-0.1392,  0.9612,  0.1144,  0.0504,  0.0482],
        [ 0.4102,  0.1144,  0.6629, -0.1484, -0.1419],
        [ 0.1805,  0.0504, -0.1484,  0.9347, -0.0624],
        [ 0.1726,  0.0482, -0.1419, -0.0624,  0.9403]])


In [12]:
shape1, shape2 = 4, 8
data = torch.randn(shape1, shape2)
torch.nn.init.orthogonal_(data)
print(data.shape)
print(data @ data.t())

torch.Size([4, 8])
tensor([[ 1.0000e+00, -1.8884e-08, -2.0549e-09,  4.1243e-08],
        [-1.8884e-08,  1.0000e+00, -3.2972e-08,  4.8322e-08],
        [-2.0549e-09, -3.2972e-08,  1.0000e+00, -1.5985e-07],
        [ 4.1243e-08,  4.8322e-08, -1.5985e-07,  1.0000e+00]])
